store {
  mode = "db"

  db {
    datasource = "druid"
    dbType = "mysql"
    driverClassName = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://host.docker.internal:3307/seata?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"
    user = "root"
    password = "root"
    minConn = 1
    maxConn = 20
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    distributedLockTable = "distributed_lock"
    queryLimit = 100
    maxWait = 5000
  }
}
